# Файл конфигурации бота

#=====================================#
#            ВК НАСТРОЙКИ             #
#=====================================#

# ID сообщества VK (минус уже стоит внутри) 
group_id: 223507839  # Замените на ID вашего сообщества

# ID сообщества логов
logs_group_id: 225643362

# ID обсуждения в логах
logs_topic_id: 53491272
from_group: 1 #если 0 отправка идет от админа если 1 то от сообщества)

# Токен доступа ВК для бота
access_token: "vk1.a.MiuRvqwfVo3VEMf_rrbAGZjdKqZL9sHu4YZbK_ok9cX0W-HVCnRfhmP9umZDtWbvehcN4MnGFSxCr_rLeG2v03TUQYZEBbLkx4PgGsDS5Jzek8WKVKT4K3rqCykIqxybZWe5v9Tq88BpZ51abUmHrZnU-K3PSkIJtO0dKzcwwxTaDLfniYjj4tzU7RS8_BaT86onTxqMH1uLQOfpMblivg"

# Токен доступа сообщества Логов (нужен токен пользователя админа)
logs_admin_token: "vk1.a.g8M8XBodXtaiyz07tyipEgu_VmIfoTVXy5-cJv-0loanTY_TOKhvNxcI6bGgqlqnZ-3tPQ3Cnskcoj2O8uHvByDBm1apu4VvKozgAe0EdQk1CZYSyMjMiq0fcNQn5PUFiBQKF_PpBliO0Q2Szaarx8CQpQAj3_8Ay99eJ33CKXEA8CXPjhqN49-ajHUV7viXqIgcfXfXa8rQ5X_It5ZsFg"

#=====================================#
#          RCON Настройки             #
#=====================================#

# Параметры ркон серверов
servers:
  grief:
    rcon_host: "149.144.69.76"
    rcon_port: 19133
    rcon_password: "DyZm8WXu"
  linux:
    rcon_host: "178.237.199.151"
    rcon_port: 19132
    rcon_password: "1X4tQcIRjT"
# список разрешенных серверов для рангов сервера
serv_perms:
  Helper:
    - "linux"
  Moderator:
    - "linux"
    - "grief"
  Support:
    - "linux"
    - "grief"
  SuperAdmin:
    - "grief"
    - "linux"
  Console:
    - "linux"
# Списки разрешённых команд для каждого ранга
permissions:
  Console:
    - "help"
  GlConsole:
    - "help"
    - "list"
  Developer:
    - "hban"
    - "hmute"
  Helper:
    - "fmute"
    - "fban"
    - "say"
    - "usrinfo"
    - "fkick"
    - "msg"
    - "list"
    - "fpardon"
    - "time"
  Moderator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "fpardon"
    - "time"
  Administrator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "time"
  SeniorAdmin:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "kill"
    - "time"
  Deputy:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Support:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Manager:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Sponsor:
    - "*"
  SuperAdmin:
    - "*"  # "*" Всё Команды
#=====================================#
#            ДРУГОЕ                   #
#=====================================#
 # Админы вк (доступ к командам "помощь админ" и до 5акков на один вк айди)
admins:
  - 000000000  # VK ID первого админа
  - 000000000  # VK ID второго админа
  - 789886979  # VK ID третьего админа
  - 000000000  # и тд

#=====================================#
#             ЗАВИСИМОСТИ             #
#=====================================#

# HlebBans
# vkProtection
# vkplaytime
# vkAuth
# 2FA_VK
# VKManager
# VKCode