# Файл конфигурации бота

#=====================================#
#            ВК НАСТРОЙКИ             #
#=====================================#

# ID сообщества VK (минус уже стоит внутри) 
group_id: 221815257  # Замените на ID вашего сообщества

# ID сообщества логов
logs_group_id: 227822604

# ID обсуждения в логах
logs_topic_id: 52560684
from_group: 1 #если 0 отправка идет от админа если 1 то от сообщества)

# Токен доступа ВК для бота
access_token: "vk1.a.8c2viGckjsuz_BB0lJdeF4JbADlL1vgoLz8wFZwQODw46GRBg1uw4B7HBhPxshcqS2zeazFgtXT3cc0bo7x2_kLQPHBeAj2lJZ0upAtcwvwj2jRo_FMDLHZ13O-P3BDqz_4SvwTMVJOhb5dKvQjb_fTkiAh6huc5cVniIBoOeJUDBxV7vywwhPq9ckDjLKlpJySukGhPOIo916TPpMyaoQ"

# Токен доступа сообщества Логов (нужен токен пользователя админа)
logs_admin_token: "vk1.a.lI1K8C96MToghQMWRfCSGQLXHXpAPg1iniMLQ-nNeC0nNHs8TKUKo-igC2c4swxYYTu8T2aGwJ7Oag87f05eUwRdq1HNSbipEZdOFs5MBHhBJTvI1owWrFhDuVRDtlzDnjQjeYCFlY9gvfAV4SQlc_cUD9_zbr7ucye5XaiTPiex3SrK__CQ_wViyjtUTKaqTfnw_dxU5Q-W0csezaIRDQ"

#=====================================#
#          RCON Настройки             #
#=====================================#

# Параметры ркон серверов
servers:
  grief:
    rcon_host: "149.154.69.76"
    rcon_port: 19133
    rcon_password: "DyZm88dWXu"
  linux:
    rcon_host: "149.154.69.76"
    rcon_port: 19100
    rcon_password: "w6QBtusWMX"
# список разрешенных серверов для рангов сервера
serv_perms:
  Helper:
    - "linux"
  Moderator:
    - "linux"
    - "grief"
  Support:
    - "linux"
    - "grief"
  SuperAdmin:
    - "grief"
    - "linux"
  Console:
    - "linux"
# Списки разрешённых команд для каждого ранга
permissions:
  Console:
    - "help"
  GlConsole:
    - "help"
    - "list"
  Developer:
    - "hban"
    - "hmute"
  Helper:
    - "fmute"
    - "fban"
    - "say"
    - "usrinfo"
    - "fkick"
    - "msg"
    - "list"
    - "fpardon"
    - "time"
  Moderator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "fpardon"
    - "time"
  Administrator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "time"
  SeniorAdmin:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "kill"
    - "time"
  Deputy:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Support:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Manager:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Sponsor:
    - "*"
  SuperAdmin:
    - "*"  # "*" Всё Команды
#=====================================#
#            ДРУГОЕ                   #
#=====================================#
 # Админы вк (доступ к командам "помощь админ" и до 5акков на один вк айди)
admins:
  - 598807327  # VK ID первого админа
  - 741773416  # VK ID второго админа
  - 789886979  # VK ID третьего админа
  - 000000000  # и тд

#=====================================#
#             ЗАВИСИМОСТИ             #
#=====================================#

# HlebBans
# vkProtection
# vkplaytime
# vkAuth
# 2FA_VK
# VKManager
# VKCode