name: VKCode
version: 1.0.0
api: [3.0.0, 4.0.0]
author: Hlebyshek
main: VKCode\VKCodePlugin
description: Plugin for generating VK codes for players.
commands:
  vkcode:
    description: Генерирует вк код для бота
    usage: /vkcode