# Файл конфигурации бота

#=====================================#
#            ВК НАСТРОЙКИ             #
#=====================================#

# ID сообщества VK (минус уже стоит внутри) 
group_id: 223507839 # Замените на ID вашего сообщества

# ID сообщества логов
logs_group_id: 225643362

# ID обсуждения в логах
logs_topic_id: 53491272
from_group: 1 #если 0 отправка идет от админа если 1 то от сообщества)

# Токен доступа ВК для бота
access_token: "vk1.a.PERsOvAjIp8B-dhoMNQJZFN57n7vRde2MRGwUYfM1TFSrlIhc0GpAX7OnCPE7FRMK0-2w18h7xFWWR5ACAYOEGCKiyLZIt8URVoryemQec_eGxrHZM85O3YvYfNckAABBzRUMU6ag_VHMTAWiu6gRO8lAAD3wVvEmyeQg4H4yCXm4y1GdBfE1Agi3Ttc7HUw21jy5lHoJg"

# Токен доступа сообщества Логов (нужен токен пользователя админа)
logs_admin_token: "vk1.a.h410M78FAc0LdWx6tP-k3rRSOq4nvLsnYXQ0oIDX8DthSQUvPy04gYa77kgAKfaqTB0oiZYwv9vtdWiiUOK0mxibiVmKUz3BHJzCxtjj-8VSgvsTLUjZSHrckB6AM0Y3VZNaVr4G9JyeNo5GHzx9JXtWLYVuNa71xOtN6tgO0fypLGpXPyizXWw-SzRsZCLoOX7jpUnn3lD1A"

#=====================================#
#          RCON Настройки             #
#=====================================#

# Параметры ркон серверов
servers:
  grief:
    rcon_host: "149.144.69.76"
    rcon_port: 19133
    rcon_password: "DyZm8WXu"
  linux:
    rcon_host: "194.226.49.228"
    rcon_port: 19132
    rcon_password: "A0iZ"
# список разрешенных серверов для рангов сервера
serv_perms:
  Helper:
    - "linux"
  Moderator:
    - "linux"
    - "grief"
  Support:
    - "linux"
    - "grief"
  SuperAdmin:
    - "grief"
    - "linux"
  Console:
    - "linux"
# Списки разрешённых команд для каждого ранга
permissions:
  Console:
    - "help"
  GlConsole:
    - "help"
    - "list"
  Developer:
    - "hban"
    - "hmute"
  Helper:
    - "fmute"
    - "fban"
    - "say"
    - "usrinfo"
    - "fkick"
    - "msg"
    - "list"
    - "fpardon"
    - "time"
  Moderator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "fpardon"
    - "time"
  Administrator:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "time"
  SeniorAdmin:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "fpardon"
    - "kill"
    - "time"
  Deputy:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Support:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Manager:
    - "fmute"
    - "fban"
    - "usrinfo"
    - "say"
    - "fkick"
    - "msg"
    - "list"
    - "tp"
    - "givemoney"
    - "groups"
    - "kill"
    - "fpardon"
    - "gamemode"
    - "give"
    - "time"
  Sponsor:
    - "*"
  SuperAdmin:
    - "*"  # "*" Всё Команды
#=====================================#
#            ДРУГОЕ                   #
#=====================================#
 # Админы вк (доступ к командам "помощь админ" и до 5акков на один вк айди)
admins:
  - 000000000  # VK ID первого админа
  - 000000000  # VK ID второго админа
  - 78986979  # VK ID третьего админа
  - 66289836  # и тд

#=====================================#
#             ЗАВИСИМОСТИ             #
#=====================================#

# HlebBans
# vkProtection
# vkplaytime
# vkAuth
# 2FA_VK
# VKManager
# VKCode