
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.0-BETA-04"

# Set default factions plugin for PureChat
# - FactionsPro / XeviousPE-Factions (§l§9-§8]§b>§7[§cXevious§aTestSrv§7]§b<§8[§9-) / null
default-factions-plugin: ~

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}
groups:
  heiter:
    chat: "&5{prefix} &f§l{display_name} &f> {msg}"
    nametag: "§l§6Хлебный §l§cХейтер × §l&f{display_name}&r"
    worlds: []
  lubitel:
    chat: "&5{prefix} §l&f{display_name} &f> {msg}"
    nametag: "&l§aЛюбитель §l§6Хлеба × &f{display_name}&r"
    worlds: []
  fanat:
    chat: "&5{prefix} &f§l{display_name} &f> {msg}"
    nametag: "§l§6Хлебный §f§lФанат × §l&f{display_name}&r"
    worlds: []
  fanatik:
    chat: "&5{prefix} &f§l{display_name} &§f> {msg}"
    nametag: "§l§6Хлебный §f§lФанатик × §l&f{display_name}&r"
    worlds: []
  bratstvo:
    chat: "&5{prefix} &c§l{display_name} &§f> {msg}"
    nametag: "§l§6Хлебное §f§lБратство × §l&c{display_name}&r"
    worlds: []
  namestnik:
    chat: "&5{prefix} &c§l{display_name} &§f> {msg}"
    nametag: "§l§6Хлебный §f§lНаместник × §l&c{display_name}&r"
    worlds: []
  bozestvo:
    chat: "&5{prefix} &c§l{display_name} §f> {msg}"
    nametag: "§l§6Хлебное §f§lБожество × §l&c{display_name}&r"
    worlds: []
...