name: Snow
version: 1.0.0
main: Snow\Hleb
api: 3.0.0
author: Hleb
description: Плагин для изменения биома загруженных чанков на снежные равнины (ICE_PLAINS).
commands:
  snow:
    description: Включить или отключить снег во всем мире.
    usage: /snow <on|off>
    permission: snow.use
permissions:
  snow.use:
    description: Разрешение на использование команды snow.
    default: op