name: VKManager
main: VKManager\VKManagerMain
version: 1.0.0
api: [3.0.0]
commands:
  givevk:
    description: "Выдать привязку ВК игроку и ранг"
    usage: "/givevk [ник_игрока]"
    permission: "vkmanager.givevk"
permissions:
  vkmanager.givevk:
    description: "Разрешение на использование команды /givevk"
    default: op